<?php
require_once __DIR__ . '/../lib/bootstrap.php';
require_role('admin');
$grade = post_string('grade', 30);
$field = post_string('field_name', 150);
$classId = get_int('class_id');
$classes = db()->query('SELECT id,title,grade_level,field_name FROM classes ORDER BY title')->fetchAll();
$where = ["a.status IN ('submitted','reviewed')", 'a.revoked_at IS NULL']; $params = [];
if ($grade !== '') { $where[] = 'c.grade_level=?'; $params[] = $grade; }
if ($field !== '') { $where[] = 'c.field_name=?'; $params[] = $field; }
if ($classId > 0) { $where[] = 'c.id=?'; $params[] = $classId; }
$whereSql = implode(' AND ', $where);
$sql = "SELECT u.id,u.full_name,u.mobile,c.title class_title,c.grade_level,c.field_name,COUNT(a.id) attempts,COALESCE(AVG(a.percentage),0) average_percentage,COALESCE(MAX(a.percentage),0) best_percentage FROM attempts a JOIN users u ON u.id=a.student_id JOIN exams e ON e.id=a.exam_id JOIN classes c ON c.id=e.class_id WHERE $whereSql GROUP BY u.id,u.full_name,u.mobile,c.id,c.title,c.grade_level,c.field_name ORDER BY average_percentage DESC,u.full_name";
$stmt = db()->prepare($sql); $stmt->execute($params); $students = $stmt->fetchAll();
$bands = ['90 تا 100' => 0, '70 تا 89' => 0, '50 تا 69' => 0, 'کمتر از 50' => 0];
foreach ($students as $student) { $score = (float)$student['average_percentage']; if ($score >= 90) $bands['90 تا 100']++; elseif ($score >= 70) $bands['70 تا 89']++; elseif ($score >= 50) $bands['50 تا 69']++; else $bands['کمتر از 50']++; }
$maxBand = max(1, ...array_values($bands));
$title = 'عملکرد دانش‌آموزان';
require __DIR__ . '/../partials/header.php';
?>
<div class="card class-toolbar"><div><span class="eyebrow">تحلیل عملکرد</span><h1>رتبه‌بندی و وضعیت دانش‌آموزان</h1><p class="muted">این گزارش بر اساس میانگین درصد کارنامه‌های معتبر تهیه می‌شود.</p></div><div class="actions"><button class="btn btn-primary" onclick="window.print()">چاپ گزارش</button><a class="btn btn-light" href="<?= e(url('admin/index.php')) ?>">بازگشت</a></div></div>
<div class="card"><form method="get" class="grid grid-3"><div class="form-group"><label>پایه</label><select name="grade"><option value="">همهٔ پایه‌ها</option><?php foreach (['دهم','یازدهم','دوازدهم'] as $option): ?><option value="<?= e($option) ?>" <?= $grade === $option ? 'selected' : '' ?>><?= e($option) ?></option><?php endforeach; ?></select></div><div class="form-group"><label>رشته</label><input name="field_name" value="<?= e($field) ?>" placeholder="مثلاً شبکه و نرم‌افزار"></div><div class="form-group"><label>کلاس</label><select name="class_id"><option value="0">همهٔ کلاس‌ها</option><?php foreach ($classes as $class): ?><option value="<?= $class['id'] ?>" <?= $classId === (int)$class['id'] ? 'selected' : '' ?>><?= e($class['title'] . ($class['grade_level'] ? ' — '.$class['grade_level'] : '')) ?></option><?php endforeach; ?></select></div><div><button class="btn btn-primary" type="submit">اعمال فیلتر</button></div></form></div>
<div class="grid grid-2"><section class="card"><div class="section-heading"><div><span class="eyebrow">توزیع نمرات</span><h2>گروه‌های عملکردی</h2></div></div><?php foreach ($bands as $label => $count): $width = $count / $maxBand * 100; ?><div class="performance-band"><div class="performance-band-head"><span><?= e($label) ?></span><strong><?= number_format($count) ?> نفر</strong></div><div class="performance-bar"><span style="width:<?= e((string)$width) ?>%"></span></div></div><?php endforeach; ?></section><section class="card"><div class="section-heading"><div><span class="eyebrow">راهنمای اقدام</span><h2>اولویت پشتیبانی</h2></div></div><p class="muted">دانش‌آموزان با میانگین کمتر از ۵۰٪ در اولویت برنامهٔ تقویتی قرار می‌گیرند. گروه ۵۰ تا ۶۹ درصد نیازمند مرور هدفمند مباحث است.</p><div class="admin-alert-stat"><strong><?= number_format($bands['کمتر از 50']) ?></strong><span>نیازمند برنامهٔ تقویتی</span></div><div class="admin-alert-stat"><strong><?= number_format($bands['50 تا 69']) ?></strong><span>نیازمند مرور هدفمند</span></div></section></div>
<section class="card"><div class="section-heading"><div><span class="eyebrow">رتبه‌بندی</span><h2>عملکرد دانش‌آموزان</h2></div><span class="muted"><?= number_format(count($students)) ?> رکورد</span></div><div class="table-wrap"><table class="table"><thead><tr><th>رتبه</th><th>دانش‌آموز</th><th>کلاس</th><th>پایه / رشته</th><th>دفعات شرکت</th><th>میانگین</th><th>بهترین درصد</th><th>وضعیت</th></tr></thead><tbody><?php if (!$students): ?><tr><td colspan="8" class="muted text-center">داده‌ای برای فیلتر انتخاب‌شده وجود ندارد.</td></tr><?php else: foreach ($students as $index => $student): $average = (float)$student['average_percentage']; ?><tr><td><?= number_format($index + 1) ?></td><td><strong><?= e($student['full_name']) ?></strong><br><small class="muted"><?= e($student['mobile']) ?></small></td><td><?= e($student['class_title']) ?></td><td><?= e(($student['grade_level'] ?? '—') . ' / ' . ($student['field_name'] ?? '—')) ?></td><td><?= number_format((int)$student['attempts']) ?></td><td><?= format_score($average) ?>%</td><td><?= format_score($student['best_percentage']) ?>%</td><td><?= e($average >= 80 ? 'قوی' : ($average >= 50 ? 'نیازمند مرور' : 'نیازمند پشتیبانی')) ?></td></tr><?php endforeach; endif; ?></tbody></table></div></section>
<?php require __DIR__ . '/../partials/footer.php'; ?>
