<?php
require_once __DIR__ . '/../lib/bootstrap.php'; require_role('admin');
if ($_SERVER['REQUEST_METHOD']==='POST') { verify_csrf(); $action=post_string('action');
  if ($action==='create') { $role=post_string('role'); $name=post_string('full_name',150); $mobile=normalize_mobile(post_string('mobile',20)); $pass=(string)($_POST['password']??''); $validation=[]; if(!in_array($role,['admin','teacher','student'],true)) $validation[]='نقش کاربر معتبر نیست.'; if($name==='') $validation[]='نام و نام خانوادگی الزامی است.'; if(strlen($mobile)<10 || strlen($mobile)>15) $validation[]='شماره موبایل باید بین ۱۰ تا ۱۵ رقم باشد.'; if(strlen($pass)<6) $validation[]='رمز عبور باید حداقل ۶ نویسه باشد.'; if($validation){flash('error',implode(' ',$validation));}else{try{$s=db()->prepare('INSERT INTO users(role,full_name,mobile,password_hash) VALUES(?,?,?,?)');$s->execute([$role,$name,$mobile,password_hash($pass,PASSWORD_DEFAULT)]);audit('create','user',(int)db()->lastInsertId());flash('success','کاربر با موفقیت ایجاد شد.');}catch(PDOException $e){flash('error','شماره موبایل تکراری است یا ثبت کاربر انجام نشد.');}}}
  if ($action==='toggle') { $id=get_int('id'); if($id!==current_user()['id']){$s=db()->prepare('UPDATE users SET is_active=1-is_active WHERE id=?');$s->execute([$id]);audit('toggle_active','user',$id);flash('success','وضعیت کاربر تغییر کرد.');} }
  redirect('admin/users.php');
}
$users=db()->query('SELECT id,role,full_name,mobile,is_active,created_at FROM users ORDER BY id DESC')->fetchAll(); $title='مدیریت کاربران';require __DIR__.'/../partials/header.php';
?><h1>مدیریت کاربران</h1><div class="card"><h2>افزودن کاربر</h2><form method="post" class="grid grid-2"><?=csrf_field()?><input type="hidden" name="action" value="create"><div class="form-group"><label>نام و نام خانوادگی</label><input name="full_name" required></div><div class="form-group"><label>شماره موبایل</label><input name="mobile" inputmode="tel" required></div><div class="form-group"><label>نقش</label><select name="role"><option value="student">دانش‌آموز</option><option value="teacher">معلم</option><option value="admin">مدیر</option></select></div><div class="form-group"><label>رمز عبور اولیه</label><input name="password" type="password" minlength="6" required></div><div><button class="btn btn-primary">ثبت کاربر</button></div></form></div><div class="card table-wrap"><table class="table"><thead><tr><th>نام</th><th>موبایل</th><th>نقش</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody><?php foreach($users as $u):?><tr><td><?=e($u['full_name'])?></td><td><?=e($u['mobile'])?></td><td><?=e($u['role'])?></td><td><?= $u['is_active']?'فعال':'غیرفعال' ?></td><td><a class="btn btn-sm btn-primary" href="<?=e(url('admin/user_edit.php?id='.$u['id']))?>">ویرایش / ریست رمز</a> <?php if((int)$u['id']!==(int)current_user()['id']):?><form method="post" style="display:inline"><?=csrf_field()?><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$u['id']?>"><button class="btn btn-sm btn-light">تغییر وضعیت</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php require __DIR__.'/../partials/footer.php'; ?>
